#!/usr/bin/env bash
set -e
echo "artisan migrate"
(cd /var/www/html && php artisan migrate --force && php artisan horizon:publish)
echo "Caching configuration... and create symlink"
(cd /var/www/html && php artisan route:cache && php artisan view:cache && php artisan config:cache && php artisan event:cache)
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf